
import React from 'react';

interface PricingModalProps {
  isOpen: boolean;
  onClose: () => void;
}

const PricingModal: React.FC<PricingModalProps> = ({ isOpen, onClose }) => {
  if (!isOpen) return null;

  return (
    <div 
        className="fixed inset-0 bg-black bg-opacity-75 flex justify-center items-center z-50 transition-opacity"
        onClick={onClose}
    >
      <div 
        className="bg-gray-800 rounded-lg shadow-2xl p-6 md:p-8 w-11/12 max-w-2xl text-gray-200 border border-gray-700 transform transition-all"
        onClick={e => e.stopPropagation()}
      >
        <div className="flex justify-between items-center mb-4">
          <h2 className="text-2xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-500">Gemini API Pricing</h2>
          <button 
            onClick={onClose} 
            className="text-gray-400 hover:text-white transition-colors"
            aria-label="Close modal"
          >
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
        <div className="prose prose-invert max-w-none text-gray-300">
          <p>
            You asked about the cost of building conversational voice apps with the Gemini API.
            Pricing for Google's Generative AI models is typically based on usage, which can be measured in different ways depending on the model and modality (text, audio, video).
          </p>
          <p>
            For a real-time conversational model like the one used in this demo (`gemini-2.5-flash-native-audio-preview-09-2025`), pricing is usually calculated per second of audio processed.
          </p>
          <ul className="list-disc pl-5 space-y-2">
            <li><strong>Audio Input:</strong> You are billed for the duration of the audio you send to the model.</li>
            <li><strong>Audio Output:</strong> You are also billed for the duration of the audio generated by the model.</li>
          </ul>
          <p>
            This usage-based model makes it cost-effective, as you only pay for what you use. However, prices are subject to change and may vary by region or model version.
          </p>
          <p className="font-semibold text-white">
            For the most accurate and up-to-date pricing information, please refer to the official Google AI Platform pricing page.
          </p>
        </div>
        <div className="mt-6 flex justify-end">
          <a
            href="https://ai.google.dev/gemini-api/docs/pricing"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-block bg-blue-600 text-white font-bold py-2 px-4 rounded-lg hover:bg-blue-700 transition-colors"
          >
            View Official Pricing
          </a>
        </div>
      </div>
    </div>
  );
};

export default PricingModal;
